- en: Foreword
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: It has been more than six years since we publicly released Kubernetes. I was
    there at the start and actually submitted the first commit to the Kubernetes project.
    (That isn’t as impressive as it sounds! It was a maintenance task as part of creating
    a clean repo for public release.) I can confidently say that the success Kubernetes
    has seen is something we had hoped for but didn’t really expect. That success
    is based on a large community of dedicated and welcoming contributors along with
    a set of practitioners who bridge the gap to the real world.
  prefs: []
  type: TYPE_NORMAL
- en: I’m lucky enough to have worked with the authors of *Production Kubernetes*
    at the startup (Heptio) that I cofounded with the mission to bring Kubernetes
    to typical enterprises. The success of Heptio is, in large part, due to my colleagues’
    efforts in creating a direct connection with real users of Kubernetes who are
    solving real problems. I’m grateful to each one of them. This book captures that
    on-the-ground experience to give teams the tools they need to really make Kubernetes
    work in a production environment.
  prefs: []
  type: TYPE_NORMAL
- en: My entire professional career has been based on building systems aimed at application
    teams and developers. It started with Microsoft Internet Explorer and then continued
    with Windows Presentation Foundation and then moved to cloud with Google Compute
    Engine and Kubernetes. Again and again I’ve seen those building platforms suffer
    from what I call “The Platform Builder’s Curse.” The people who are building the
    platforms are focused on a longer time horizon and the challenge of building a
    foundation that will, hopefully, last decades. But that focus creates a blind
    spot to the problems that users are having *right now*. Oftentimes we are so busy
    building a thing we don’t have the time and problems that lead us to actually
    use the thing we are building.
  prefs: []
  type: TYPE_NORMAL
- en: The only way to defeat the platform builder’s curse is to actively seek information
    from outside our platform-builder bubble. This is what the Heptio Field Engineering
    team (and later the VMware Kubernetes Architecture Team—KAT) did for me. Beyond
    helping a wide variety of customers across industries be successful with Kubernetes,
    the team is a critical window into the reality of how the “theory” of our platform
    is applied.
  prefs: []
  type: TYPE_NORMAL
- en: This problem is only exacerbated by the thriving ecosystem that has been built
    up around Kubernetes and the Cloud Native Computing Foundation (CNCF). This includes
    both projects that are part of the CNCF and those that are in the larger orbit.
    I describe this ecosystem as “beautiful chaos.” It is a rainforest of projects
    with varying degrees of overlap and maturity. This is what innovation looks like!
    But, just like exploring a rainforest, exploring this ecosystem requires dedication
    and time, and it comes with risks. New users to the world of Kubernetes often
    don’t have the time or capacity to become experts in the larger ecosystem.
  prefs: []
  type: TYPE_NORMAL
- en: '*Production Kubernetes* maps out the parts of that ecosystem, when individual
    tools and projects are appropriate, and demonstrates how to evaluate the right
    tool for the problems the reader is facing. This advice goes beyond just telling
    readers to use a particular tool. It is a larger framework for understanding the
    problem a class of tools solves, knowing whether you have that problem, being
    familiar with the strengths and weaknesses to different approaches, and offering
    practical advice for getting going. For those looking to take Kubernetes into
    production, this information is gold!'
  prefs: []
  type: TYPE_NORMAL
- en: In conclusion, I’d like to send a big “Thank You” to Josh, Rich, Alex, and John.
    Their experience has made many customers directly successful, has taught me a
    lot about the thing that we started more than six years ago, and now, through
    this book, will provide critical advice to countless more users.
  prefs: []
  type: TYPE_NORMAL
- en: Joe Beda
  prefs: []
  type: TYPE_NORMAL
- en: Principal Engineer for VMware Tanzu, Cocreator of Kubernetes,
  prefs: []
  type: TYPE_NORMAL
- en: Seattle, January 2021
  prefs: []
  type: TYPE_NORMAL
