- en: Foreword
  id: totrans-0
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 前言
- en: It has been more than six years since we publicly released Kubernetes. I was
    there at the start and actually submitted the first commit to the Kubernetes project.
    (That isn’t as impressive as it sounds! It was a maintenance task as part of creating
    a clean repo for public release.) I can confidently say that the success Kubernetes
    has seen is something we had hoped for but didn’t really expect. That success
    is based on a large community of dedicated and welcoming contributors along with
    a set of practitioners who bridge the gap to the real world.
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: Kubernetes 自公开发布以来已经超过六年了。我参与了初始阶段，并且实际上提交了 Kubernetes 项目的第一个提交。（这并没有听起来那么令人印象深刻！那只是一个为公开发布创建干净代码库的维护任务。）我可以自信地说，Kubernetes
    取得的成功是我们所希望但并不完全预料到的。这一成功基于一个大型社区的奉献和欢迎贡献者，以及一群能够弥合与现实世界之间鸿沟的实践者。
- en: I’m lucky enough to have worked with the authors of *Production Kubernetes*
    at the startup (Heptio) that I cofounded with the mission to bring Kubernetes
    to typical enterprises. The success of Heptio is, in large part, due to my colleagues’
    efforts in creating a direct connection with real users of Kubernetes who are
    solving real problems. I’m grateful to each one of them. This book captures that
    on-the-ground experience to give teams the tools they need to really make Kubernetes
    work in a production environment.
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: 我很幸运能够与《生产 Kubernetes》的作者合作，他们在我与共同创立的初创公司（Heptio），致力于将 Kubernetes 带入典型企业的使命中，留下了深刻的印象。Heptio
    的成功很大程度上归功于我的同事们努力与使用 Kubernetes 解决实际问题的真实用户直接联系。我对每一位同事都心怀感激。这本书捕捉了这种实地经验，为团队提供了在生产环境中真正让
    Kubernetes 发挥作用所需的工具。
- en: My entire professional career has been based on building systems aimed at application
    teams and developers. It started with Microsoft Internet Explorer and then continued
    with Windows Presentation Foundation and then moved to cloud with Google Compute
    Engine and Kubernetes. Again and again I’ve seen those building platforms suffer
    from what I call “The Platform Builder’s Curse.” The people who are building the
    platforms are focused on a longer time horizon and the challenge of building a
    foundation that will, hopefully, last decades. But that focus creates a blind
    spot to the problems that users are having *right now*. Oftentimes we are so busy
    building a thing we don’t have the time and problems that lead us to actually
    use the thing we are building.
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: 我的整个职业生涯都致力于构建面向应用团队和开发者的系统。从 Microsoft Internet Explorer 开始，然后是 Windows Presentation
    Foundation，再到云端的 Google Compute Engine 和 Kubernetes。我一次又一次地看到那些构建平台的人遭受我所称的“平台建设者的诅咒”。构建平台的人通常关注更长时间的视角和构建一个有望持续数十年的基础的挑战。但是这种关注会使他们忽视用户此刻正在遇到的问题。我们常常忙于构建某事物，却没有时间和问题去真正使用我们正在构建的东西。
- en: The only way to defeat the platform builder’s curse is to actively seek information
    from outside our platform-builder bubble. This is what the Heptio Field Engineering
    team (and later the VMware Kubernetes Architecture Team—KAT) did for me. Beyond
    helping a wide variety of customers across industries be successful with Kubernetes,
    the team is a critical window into the reality of how the “theory” of our platform
    is applied.
  id: totrans-4
  prefs: []
  type: TYPE_NORMAL
  zh: 打败平台建设者诅咒的唯一方法是积极寻求来自我们平台建设者泡泡之外的信息。这就是 Heptio 田野工程团队（后来是 VMware Kubernetes
    架构团队—KAT）为我所做的事情。除了帮助各行各业的广泛客户成功使用 Kubernetes 外，该团队还是实际应用我们平台“理论”的关键窗口。
- en: This problem is only exacerbated by the thriving ecosystem that has been built
    up around Kubernetes and the Cloud Native Computing Foundation (CNCF). This includes
    both projects that are part of the CNCF and those that are in the larger orbit.
    I describe this ecosystem as “beautiful chaos.” It is a rainforest of projects
    with varying degrees of overlap and maturity. This is what innovation looks like!
    But, just like exploring a rainforest, exploring this ecosystem requires dedication
    and time, and it comes with risks. New users to the world of Kubernetes often
    don’t have the time or capacity to become experts in the larger ecosystem.
  id: totrans-5
  prefs: []
  type: TYPE_NORMAL
  zh: Kubernetes 周围建立起来的繁荣生态系统和云原生计算基金会（CNCF）进一步加剧了这一问题。这包括 CNCF 的项目以及更大范围内的项目。我将这个生态系统描述为“美丽的混沌”。这是一个具有不同重叠程度和成熟度的项目丛林。这就是创新的样子！但是，就像探索丛林一样，探索这个生态系统需要投入时间和精力，并伴随着风险。对于
    Kubernetes 的新用户来说，通常没有时间或能力成为更大生态系统的专家。
- en: '*Production Kubernetes* maps out the parts of that ecosystem, when individual
    tools and projects are appropriate, and demonstrates how to evaluate the right
    tool for the problems the reader is facing. This advice goes beyond just telling
    readers to use a particular tool. It is a larger framework for understanding the
    problem a class of tools solves, knowing whether you have that problem, being
    familiar with the strengths and weaknesses to different approaches, and offering
    practical advice for getting going. For those looking to take Kubernetes into
    production, this information is gold!'
  id: totrans-6
  prefs: []
  type: TYPE_NORMAL
  zh: '*Production Kubernetes* 绘制了该生态系统的各个部分，展示了在什么情况下使用单个工具和项目是合适的，并演示了如何评估适合读者面临问题的正确工具。这些建议不仅仅是告诉读者使用特定工具，它是一个更大的框架，用于理解一类工具解决的问题，知道是否存在这个问题，熟悉不同方法的优缺点，并提供实际建议来启动。对于那些希望将
    Kubernetes 应用于生产环境的人来说，这些信息非常宝贵！'
- en: In conclusion, I’d like to send a big “Thank You” to Josh, Rich, Alex, and John.
    Their experience has made many customers directly successful, has taught me a
    lot about the thing that we started more than six years ago, and now, through
    this book, will provide critical advice to countless more users.
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: 总结一下，我想对 Josh、Rich、Alex 和 John 表示衷心的“谢谢”。他们的经验直接帮助了许多客户取得成功，让我对我们六年前开始的事情有了更多的了解，现在通过这本书，将为无数更多的用户提供关键建议。
- en: Joe Beda
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: Joe Beda
- en: Principal Engineer for VMware Tanzu, Cocreator of Kubernetes,
  id: totrans-9
  prefs: []
  type: TYPE_NORMAL
  zh: VMware Tanzu 的首席工程师，Kubernetes 的联合创始人，
- en: Seattle, January 2021
  id: totrans-10
  prefs: []
  type: TYPE_NORMAL
  zh: 西雅图，2021年1月
