- en: Preface
  id: totrans-0
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 前言
- en: Kubernetes is a remarkably powerful technology and has achieved a meteoric rise
    in popularity. It has formed the basis for genuine advances in the way we manage
    software deployments. API-driven software and distributed systems were well established,
    if not widely adopted, when Kubernetes emerged. It delivered excellent renditions
    of these principles, which are foundational to its success, but it also delivered
    something else that is vital. In the recent past, software that autonomously converged
    on declared, desired state was possible only in giant technology companies with
    the most talented engineering teams. Now, highly available, self-healing, autoscaling
    software deployments are within reach of every organization, thanks to the Kubernetes
    project. There is a future in front of us where software systems accept broad,
    high-level directives from us and execute upon them to deliver desired outcomes
    by discovering conditions, navigating changing obstacles, and repairing problems
    without our intervention. Furthermore, these systems will do it faster and more
    reliably than we ever could with manual operations. Kubernetes has brought us
    all much closer to that future. However, that power and capability comes at the
    cost of some additional complexity. The desire to share our experiences helping
    others navigate that complexity is why we decided to write this book.
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: Kubernetes 是一项非常强大的技术，并且在流行度上迅速崛起。它已经成为我们管理软件部署方式上真正进步的基础。在 Kubernetes 出现之时，虽然
    API 驱动的软件和分布式系统已经得到了确立，但尚未被广泛采用。它出色地实现了这些原则，这些原则是其成功的基石，但它也带来了一些至关重要的其他东西。在不久的过去，只有拥有最杰出工程团队的大型科技公司才能实现自动收敛于声明的期望状态的软件。如今，由于
    Kubernetes 项目，高可用、自我修复、自动扩展的软件部署对每个组织来说都是可实现的。在我们面前有一个未来，软件系统能接受我们的广泛高级指令，并执行它们以提供预期的结果，通过发现条件、应对变化的障碍和自动修复问题，无需我们干预。而且，这些系统比我们手工操作更快速、更可靠。Kubernetes
    已经让我们离这个未来更近了一步。然而，这种强大和能力是以一些额外复杂性为代价的。我们决定撰写这本书，是因为我们希望分享我们的经验，帮助他人应对这种复杂性。
- en: You should read this book if you want to use Kubernetes to build a production-grade
    application platform. If you are looking for a book to help you get started with
    Kubernetes, or a text on how Kubernetes works, this is not the right book. There
    is a wealth of information on these subjects in other books, in the official documentation,
    and in countless blog posts and the source code itself. We recommend pairing the
    consumption of this book with your own research and testing for the solutions
    we discuss, so we rarely dive deeply into *step-by-step* tutorial style examples.
    We try to cover as much theory as necessary and leave most of the *implementation*
    as an exercise to the reader.
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: 如果你想要使用 Kubernetes 构建一个符合生产标准的应用平台，你应该阅读这本书。如果你正在寻找一本帮助你入门 Kubernetes 或者关于 Kubernetes
    工作原理的书籍，那么这本书不适合。关于这些主题有大量信息可以在其他书籍、官方文档以及无数的博客文章和源代码中找到。我们建议你在阅读本书的同时进行自己的研究和测试，以验证我们讨论的解决方案，因此我们很少深入进行*逐步*教程样式的例子。我们尽量涵盖必要的理论，并把大部分*实现*留给读者自己来练习。
- en: Throughout this book, you’ll find guidance in the form of options, tooling,
    patterns, and practices. It’s important to read this guidance with an understanding
    of how the authors view the practice of building application platforms. We are
    engineers and architects who get deployed across many Fortune 500 companies to
    help them take their platform aspirations from idea to production. We have been
    using Kubernetes as the foundation for getting there since as early as 2015, when
    Kubernetes reached `1.0`. We have tried as much as possible to focus on patterns
    and philosophy rather than on tools, as new tooling appears quicker than we can
    write! However, we inevitably have to demonstrate those patterns with the most
    appropriate tool du jour.
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: 在这本书中，你将会找到关于选项、工具、模式和实践的指导。重要的是，理解作者如何看待构建应用平台的实践。我们是工程师和架构师，被派往许多财富500强公司，帮助他们从构想到生产的平台愿景。自从
    Kubernetes 在2015年达到`1.0`版本以来，我们就把它作为实现这一目标的基础。我们尽可能地专注于模式和哲学，而不是工具，因为新的工具出现得比我们写书更快！然而，我们不可避免地必须用当下最合适的工具来演示这些模式。
- en: We have had major successes guiding teams through their cloud native journey
    to completely transform how they build and deliver software. That said, we have
    also had our doses of failure. A common reason for failure is an organization’s
    misconception of what Kubernetes will solve for. This is why we dive so deep into
    the concept early on. Over this time we’ve found several areas to be especially
    interesting for our customers. Conversations that help customers get further on
    their path to production, or even help them define it, have become routine. These
    conversations became so common that we decided maybe it’s time to write a book!
  id: totrans-4
  prefs: []
  type: TYPE_NORMAL
  zh: 我们已成功引导团队通过云原生之旅，彻底改变他们构建和交付软件的方式。话虽如此，我们也曾经历失败。失败的一个常见原因是组织对 Kubernetes 能解决什么存在误解。这就是为什么我们早期深入探讨这个概念的原因。在此期间，我们发现几个领域对我们的客户尤其有趣。帮助客户在他们通往生产环境的道路上更进一步，甚至帮助他们定义这条道路的对话已成常态。这些对话变得如此普遍，以至于我们决定也许是时候写一本书了！
- en: While we’ve made this journey to production with organizations time and time
    again, there is only one key consistency across them. This is that the road *never*
    looks the same, no matter how badly we sometimes want it to. With this in mind,
    we want to set the expectation that if you’re going into this book looking for
    the “5-step program” for getting to production or the “10 things every Kubernetes
    user should know,” you’re going to be frustrated. We’re here to talk about the
    many decision points and the traps we’ve seen, and to back it up with concrete
    examples and anecdotes when appropriate. Best practices exist but must always
    be viewed through the lens of pragmatism. There is no one-size-fits-all approach,
    and “It depends” is an entirely valid answer to many of the questions you’ll inevitably
    confront on the journey.
  id: totrans-5
  prefs: []
  type: TYPE_NORMAL
  zh: 尽管我们一次又一次地与组织一同走向生产，但其中有一个关键的一致性特征。这就是，无论我们多么希望如此，道路*永远*不会看起来相同。基于此，我们想要设定一个期望：如果你打算通过这本书找到通往生产环境的“5步计划”或“每个
    Kubernetes 用户应该知道的10件事”，你将会感到沮丧。我们在这里讨论许多决策点和我们见过的陷阱，并在适当时用具体的例子和轶事加以支持。最佳实践确实存在，但必须始终从实用主义的角度来看待。没有一种适合所有情况的方法，“这取决于情况”是你将不可避免地面对的许多问题的完全有效的答案。
- en: That said, we highly encourage you to *challenge* this book! When working with
    clients we’re always encouraging them to challenge and augment our guidance. Knowledge
    is fluid, and we are always updating our approaches based on new features, information,
    and constraints. You should continue that trend; as the cloud native space continues
    to evolve, you’ll certainly decide to take alternative roads from what we recommended.
    We’re here to tell you about the ones we’ve been down so you can weigh our perspective
    against your own.
  id: totrans-6
  prefs: []
  type: TYPE_NORMAL
  zh: 话虽如此，我们强烈建议你*挑战*本书！在与客户合作时，我们总是鼓励他们挑战和完善我们的指导。知识是流动的，我们始终根据新特性、信息和约束更新我们的方法。你应该继续这种趋势；随着云原生空间的不断发展，你肯定会决定采取与我们推荐的不同路径。我们在这里告诉你我们曾经走过的路，这样你就可以权衡我们的观点和你自己的观点。
- en: Conventions Used in This Book
  id: totrans-7
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 本书中使用的约定
- en: 'The following typographical conventions are used in this book:'
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: 本书中使用以下排版约定：
- en: '*Italic*'
  id: totrans-9
  prefs: []
  type: TYPE_NORMAL
  zh: '*Italic*'
- en: Indicates new terms, URLs, email addresses, filenames, and file extensions.
  id: totrans-10
  prefs: []
  type: TYPE_NORMAL
  zh: 表示新术语、网址、电子邮件地址、文件名和文件扩展名。
- en: '`Constant width`'
  id: totrans-11
  prefs: []
  type: TYPE_NORMAL
  zh: '`Constant width`'
- en: Used for program listings, as well as within paragraphs to refer to program
    elements such as variable or function names, databases, data types, environment
    variables, statements, and keywords.
  id: totrans-12
  prefs: []
  type: TYPE_NORMAL
  zh: 用于程序清单，以及在段落内引用程序元素，如变量或函数名、数据库、数据类型、环境变量、语句和关键字。
- en: '**`Constant width bold`**'
  id: totrans-13
  prefs: []
  type: TYPE_NORMAL
  zh: '**`Constant width bold`**'
- en: Shows commands or other text that should be typed literally by the user.
  id: totrans-14
  prefs: []
  type: TYPE_NORMAL
  zh: 显示用户应按字面意义输入的命令或其他文本。
- en: '*`Constant width italic`*'
  id: totrans-15
  prefs: []
  type: TYPE_NORMAL
  zh: '*`Constant width italic`*'
- en: Shows text that should be replaced with user-supplied values or by values determined
    by context.
  id: totrans-16
  prefs: []
  type: TYPE_NORMAL
  zh: 显示应由用户提供的值或由上下文确定的值替换的文本。
- en: Kubernetes kinds are capitalized, as in Pod, Service, and StatefulSet.
  id: totrans-17
  prefs: []
  type: TYPE_NORMAL
  zh: Kubernetes 的类型名称采用大写，如 Pod、Service 和 StatefulSet。
- en: Tip
  id: totrans-18
  prefs:
  - PREF_H6
  type: TYPE_NORMAL
  zh: 提示
- en: This element signifies a tip or suggestion.
  id: totrans-19
  prefs: []
  type: TYPE_NORMAL
  zh: 此元素表示提示或建议。
- en: Note
  id: totrans-20
  prefs:
  - PREF_H6
  type: TYPE_NORMAL
  zh: 注意
- en: This element signifies a general note.
  id: totrans-21
  prefs: []
  type: TYPE_NORMAL
  zh: 此元素表示一般提示。
- en: Warning
  id: totrans-22
  prefs:
  - PREF_H6
  type: TYPE_NORMAL
  zh: 警告
- en: This element indicates a warning or caution.
  id: totrans-23
  prefs: []
  type: TYPE_NORMAL
  zh: 此元素表示警告或注意。
- en: Using Code Examples
  id: totrans-24
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 使用代码示例
- en: Supplemental material (code examples, exercises, etc.) is available for download
    and discussion at [*https://github.com/production-kubernetes*](https://github.com/production-kubernetes).
  id: totrans-25
  prefs: []
  type: TYPE_NORMAL
  zh: 补充材料（代码示例、练习等）可在 [*https://github.com/production-kubernetes*](https://github.com/production-kubernetes)
    下载和讨论。
- en: If you have a technical question or a problem using the code examples, please
    send email to [*bookquestions@oreilly.com*](mailto:bookquestions@oreilly.com).
  id: totrans-26
  prefs: []
  type: TYPE_NORMAL
  zh: 如果您有技术问题或使用代码示例时遇到问题，请发送电子邮件至 [*bookquestions@oreilly.com*](mailto:bookquestions@oreilly.com)。
- en: This book is here to help you get your job done. In general, if example code
    is offered with this book, you may use it in your programs and documentation.
    You do not need to contact us for permission unless you’re reproducing a significant
    portion of the code. For example, writing a program that uses several chunks of
    code from this book does not require permission. Selling or distributing examples
    from O’Reilly books does require permission. Answering a question by citing this
    book and quoting example code does not require permission. Incorporating a significant
    amount of example code from this book into your product’s documentation does require
    permission.
  id: totrans-27
  prefs: []
  type: TYPE_NORMAL
  zh: 这本书旨在帮助您完成工作。一般情况下，如果书中提供了示例代码，您可以在自己的程序和文档中使用它们，无需事先联系我们获得许可，除非您要复制代码的大部分。例如，编写一个使用本书中多个代码片段的程序不需要许可。销售或分发从
    O’Reilly 图书中提取的示例代码需要获得许可。引用本书并引用示例代码来回答问题不需要许可。将本书大量示例代码整合到产品文档中需要获得许可。
- en: 'We appreciate, but generally do not require, attribution. An attribution usually
    includes the title, author, publisher, and ISBN. For example: “*Production Kubernetes*
    by Josh Rosso, Rich Lander, Alexander Brand, and John Harris (O’Reilly). Copyright
    2021 Josh Rosso, Rich Lander, Alexander Brand, and John Harris, 978-1-492-09231-5.”'
  id: totrans-28
  prefs: []
  type: TYPE_NORMAL
  zh: 我们感谢您的支持，但通常不要求署名。署名通常包括标题、作者、出版商和 ISBN。例如：“*Production Kubernetes* by Josh
    Rosso, Rich Lander, Alexander Brand, and John Harris (O’Reilly). Copyright 2021
    Josh Rosso, Rich Lander, Alexander Brand, and John Harris, 978-1-492-09231-5.”
- en: If you feel your use of code examples falls outside fair use or the permission
    given above, feel free to contact us at [*permissions@oreilly.com*](mailto:permissions@oreilly.com).
  id: totrans-29
  prefs: []
  type: TYPE_NORMAL
  zh: 如果您认为使用代码示例超出了公平使用范围或上述许可，请随时通过 [*permissions@oreilly.com*](mailto:permissions@oreilly.com)
    联系我们。
- en: O’Reilly Online Learning
  id: totrans-30
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: O’Reilly 在线学习
- en: Note
  id: totrans-31
  prefs:
  - PREF_H6
  type: TYPE_NORMAL
  zh: 注意
- en: For more than 40 years, [*O’Reilly Media*](http://oreilly.com) has provided
    technology and business training, knowledge, and insight to help companies succeed.
  id: totrans-32
  prefs: []
  type: TYPE_NORMAL
  zh: 超过 40 年来，[*O’Reilly Media*](http://oreilly.com) 一直为公司提供技术和商业培训、知识和洞察力，帮助它们取得成功。
- en: Our unique network of experts and innovators share their knowledge and expertise
    through books, articles, and our online learning platform. O’Reilly’s online learning
    platform gives you on-demand access to live training courses, in-depth learning
    paths, interactive coding environments, and a vast collection of text and video
    from O’Reilly and 200+ other publishers. For more information, visit [*http://oreilly.com*](http://oreilly.com).
  id: totrans-33
  prefs: []
  type: TYPE_NORMAL
  zh: 我们独特的专家和创新者网络通过书籍、文章和我们的在线学习平台分享他们的知识和专业知识。O’Reilly 的在线学习平台让您随时访问现场培训课程、深入学习路径、交互式编码环境以及来自
    O’Reilly 和其他 200 多家出版商的大量文本和视频。获取更多信息，请访问：[*http://oreilly.com*](http://oreilly.com)。
- en: How to Contact Us
  id: totrans-34
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 如何联系我们
- en: 'Please address comments and questions concerning this book to the publisher:'
  id: totrans-35
  prefs: []
  type: TYPE_NORMAL
  zh: 有关此书的评论和问题，请联系出版社：
- en: O’Reilly Media, Inc.
  id: totrans-36
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: O’Reilly Media, Inc.
- en: 1005 Gravenstein Highway North
  id: totrans-37
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 1005 Gravenstein Highway North
- en: Sebastopol, CA 95472
  id: totrans-38
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Sebastopol, CA 95472
- en: 800-998-9938 (in the United States or Canada)
  id: totrans-39
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 800-998-9938（美国或加拿大）
- en: 707-829-0515 (international or local)
  id: totrans-40
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 707-829-0515（国际或本地）
- en: 707-829-0104 (fax)
  id: totrans-41
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 707-829-0104（传真）
- en: We have a web page for this book, where we list errata, examples, and any additional
    information. You can access this page at [*https://oreil.ly/production-kubernetes*](https://oreil.ly/production-kubernetes).
  id: totrans-42
  prefs: []
  type: TYPE_NORMAL
  zh: 我们为这本书创建了一个网页，上面列出了勘误、示例和任何额外信息。您可以访问这个页面：[*https://oreil.ly/production-kubernetes*](https://oreil.ly/production-kubernetes)。
- en: Email [*bookquestions@oreilly.com*](mailto:bookquestions@oreilly.com) to comment
    or ask technical questions about this book.
  id: totrans-43
  prefs: []
  type: TYPE_NORMAL
  zh: 通过电子邮件 [*bookquestions@oreilly.com*](mailto:bookquestions@oreilly.com) 发表评论或提出关于本书的技术问题。
- en: For news and information about our books and courses, visit [*http://oreilly.com*](http://oreilly.com).
  id: totrans-44
  prefs: []
  type: TYPE_NORMAL
  zh: 有关我们的书籍和课程的新闻和信息，请访问 [*http://oreilly.com*](http://oreilly.com)。
- en: 'Find us on Facebook: [*http://facebook.com/oreilly*](http://facebook.com/oreilly)'
  id: totrans-45
  prefs: []
  type: TYPE_NORMAL
  zh: 在 Facebook 上找到我们：[*http://facebook.com/oreilly*](http://facebook.com/oreilly)
- en: 'Follow us on Twitter: [*http://twitter.com/oreillymedia*](http://twitter.com/oreillymedia)'
  id: totrans-46
  prefs: []
  type: TYPE_NORMAL
  zh: 在 Twitter 关注我们：[*http://twitter.com/oreillymedia*](http://twitter.com/oreillymedia)
- en: 'Watch us on YouTube: [*http://youtube.com/oreillymedia*](http://youtube.com/oreillymedia)'
  id: totrans-47
  prefs: []
  type: TYPE_NORMAL
  zh: 在 YouTube 观看我们：[*http://youtube.com/oreillymedia*](http://youtube.com/oreillymedia)
- en: Acknowledgments
  id: totrans-48
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 致谢
- en: The authors would like to thank Katie Gamanji, Michael Goodness, Jim Weber,
    Jed Salazar, Tony Scully, Monica Rodriguez, Kris Dockery, Ralph Bankston, Steve
    Sloka, Aaron Miller, Tunde Olu-Isa, Alex Withrow, Scott Lowe, Ryan Chapple, and
    Kenan Dervisevic for their reviews and feedback on the manuscript. Thanks to Paul
    Lundin for encouraging the development of this book and for building the incredible
    Field Engineering team at Heptio. Everyone on the team has contributed in some
    way by collaborating on and developing many of the ideas and experiences we cover
    over the next 450 pages. Thanks also to Joe Beda, Scott Buchanan, Danielle Burrow,
    and Tim Coventry-Cox at VMware for their support as we initiated and developed
    this project. Finally, thanks to John Devins, Jeff Bleiel, and Christopher Faucher
    at O’Reilly for their ongoing support and feedback.
  id: totrans-49
  prefs: []
  type: TYPE_NORMAL
  zh: 作者们感谢 Katie Gamanji、Michael Goodness、Jim Weber、Jed Salazar、Tony Scully、Monica
    Rodriguez、Kris Dockery、Ralph Bankston、Steve Sloka、Aaron Miller、Tunde Olu-Isa、Alex
    Withrow、Scott Lowe、Ryan Chapple 和 Kenan Dervisevic 对手稿的评论和反馈。感谢 Paul Lundin 在书籍开发过程中的鼓励，并且在
    Heptio 建立了出色的 Field Engineering 团队。团队中的每个人都通过协作和开发了我们接下来450页所涵盖的许多想法和经验做出了贡献。最后，感谢
    VMware 的 Joe Beda、Scott Buchanan、Danielle Burrow 和 Tim Coventry-Cox 在我们启动和开发此项目时的支持。最后，感谢
    O’Reilly 的 John Devins、Jeff Bleiel 和 Christopher Faucher 持续的支持和反馈。
- en: 'The authors would also like to personally thank the following people:'
  id: totrans-50
  prefs: []
  type: TYPE_NORMAL
  zh: 作者们还要特别感谢以下人士：
- en: 'Josh: I would like to thank Jessica Appelbaum for her absurd levels of support,
    specifically blueberry pancakes, while I dedicated my time to this book. I’d also
    like to thank my mom, Angela, and dad, Joe, for being my foundation growing up.'
  id: totrans-51
  prefs: []
  type: TYPE_NORMAL
  zh: Josh：我要感谢 Jessica Appelbaum，在我撰写本书期间给予我的大力支持，特别是提供的蓝莓煎饼。我还要感谢我的妈妈 Angela 和爸爸
    Joe，在我成长过程中为我提供坚实的支持。
- en: 'Rich: I would like to thank my wife, Taylor, and children, Raina, Jasmine,
    Max, and John, for their support and understanding while I took time to work on
    this book. I would also like to thank my Mum, Jenny, and my Dad, Norm, for being
    great role models.'
  id: totrans-52
  prefs: []
  type: TYPE_NORMAL
  zh: Rich：我要感谢我的妻子 Taylor 和孩子们 Raina、Jasmine、Max 和 John，在我撰写本书期间给予我的支持和理解。我还要感谢我的妈妈
    Jenny 和爸爸 Norm，他们是我很好的榜样。
- en: 'Alexander: My love and thanks to my amazing wife, Anais, who was incredibly
    supportive as I dedicated time to writing this book. I also thank my family, friends,
    and colleagues who have helped me become who I am today.'
  id: totrans-53
  prefs: []
  type: TYPE_NORMAL
  zh: Alexander：我爱你，感谢我的不可思议的妻子 Anais，在我撰写本书期间给予我的极大支持。我还感谢我的家人、朋友和同事，是他们帮助我成为今天的我。
- en: 'John: I’d like to thank my beautiful wife, Christina, for her love and patience
    during my work on this book. Also thanks to my close friends and family for their
    ongoing support and encouragement over the years.'
  id: totrans-54
  prefs: []
  type: TYPE_NORMAL
  zh: John：我要感谢我美丽的妻子 Christina，在我撰写本书期间给予我的爱和耐心。也感谢我的亲密朋友和家人多年来的支持和鼓励。
